spring:
  application:
    name: gmt_mono

  profiles:
    active: dev

  datasource:
    url: ${gmt.datasource.url}
    username: ${gmt.datasource.username}
    password: ${gmt.datasource.password}

  data:
    redis:
      host: ${gmt.redis.host}
      port: ${gmt.redis.port}
      password: ${gmt.redis.password}
      database: ${gmt.redis.database}

  rabbitmq:
    host: ${gmt.rabbitmq.host}
    port: ${gmt.rabbitmq.port}
    username: ${gmt.rabbitmq.username}
    password: ${gmt.rabbitmq.password}
    listener:
      simple:
        acknowledge-mode: ${gmt.rabbitmq.listener.simple.acknowledge-mode}
        retry:
          enabled: ${gmt.rabbitmq.listener.simple.retry.enabled}
          initial-interval: ${gmt.rabbitmq.listener.simple.retry.initial-interval}
          max-attempts: ${gmt.rabbitmq.listener.simple.retry.max-attempts}
          max-interval: ${gmt.rabbitmq.listener.simple.retry.max-interval}
          multiplier: ${gmt.rabbitmq.listener.simple.retry.multiplier}

  cloud:
    sentinel:
      transport:
        dashboard: ${gmt.sentinel.transport.dashboard}
        port: ${gmt.sentinel.transport.port}

server:
  port: 8080

knife4j:
  enable: true

alipay:
  app-id: ${gmt.alipay.app-id}
  app-private-key: ${gmt.alipay.app-private-key}
  alipay-public-key: ${gmt.alipay.alipay-public-key}
  notify-url: ${gmt.alipay.notify-url}
  return-url: ${gmt.alipay.return-url}