gmt:
  dataSource:
    url: jdbc:mysql://localhost:3306/gmt_mono_data?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: lxy

  redis:
    host: localhost
    port: 6379
    password: lxy
    database: 0

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  sentinel:
    transport:
      dashboard: localhost:8081
      port: 8719

  alipay:
    app-id: 9021000150668243
    app-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC3aRWcLkGqwfdIRqFZ1/hTOi+lU3cuGtnqgjfDf61BknQAf5zIaoMtNOA+yUFcBvgZIH1dxkZ7L62ICF5Puj3Ywo1q3Vs1dX5Gg7qyf99AblZX42L6od7InI6/MlKu5C5lduicHZsXUUuqTiavS1AuMTNId71z62nWCGVfdUrF8W/MVnSlqTggT4zxv//d/t5O++pO9PKhE0izjZUAQXm8G4L8XFLSsng3BUWeguWVd2lp2qo6EFNCax/EG1hrbWqt7DIJ8BlHtTRpGF8XjgC/zQ/3ObWiz4i7O/N6KqBbNCsGbVXAyI+6dlBxhfPpXBSm1jUu5kJwJnEwrKF0/kxdAgMBAAECggEBAI3/QqbXPSnp3/xKCpOXXH97FfZGh4ffbAVeabPm/ok8zKiyI/0aUZLHVDHn+L05/AzgFY9reZfX0t71s6bARy+xeHFbDUl3PJt1Uy7tRzgH9Ls4paHrfqMMaovmdxNGQBF4HSD43uEPpKgmt1aR1XLdzpl1cuzzPs5hU7KzCX/zW+ZWMaQH7a2OT8vi9x7vnGoqFia1U2BcWXJm9XNiYyIo3l59Da53ek6S1O51ox2ZUbLu6xyx0WzLaFY3FfMgnXkGZyYUI13a0+DNAkZqLRnE1knIj/DXK3OPS0IHs7ifHY3KTWHxw7eJxH0P6RN/4a0D3poinHdPgyXWycZXbnUCgYEA4CkMcajzJb7Oo49cREHPmpnvYyO5wiBp0iOSqyD5ONPvj6N8vzORvMeBhWYbUjAVKJk5LL1lkrAVleGbXTF1aND9Jy73HJndLF1sPDoiSvd/nudDWKUDQlmtcK62vxrkg0pEuzvO8mI9UBDbbaL7HH/LJBGbvOsDeMJZ9osgf2MCgYEA0XZIjbw85GT2+6XVQUTf9Wse7AsMjya/ryXtn+jWzzxW6i7QAW7G1sLqNfv1Hgh66eqQ9gyoqa614WJt/6UpPhoqa9IumPYVVbEKvNL0SYh1PV0fcxadqKMaZsFyoT+R/yXD5BNTdx+8lMEh+CNZPSY2iP+y1nq6XcWLJzT/MT8CgYA4xIx/OE8jbvf72fF+47/EollKnSCM9hJ2gkXBit8yshGIKdoMve2ZhljZxKsEnGKvXmZpWymfBXLh+zmSV1Upj0udIbq5BopJkvs3IW3P2G/8eQrIJzn1Eqrmz4g+S3w1d5iCZjoZjiGC5lH7qPu5EvAKGV98b3P4oBeSZVd8iwKBgDNrLfRdOTV384li9C7JkZDVcwnOzI53nKaKUQLoTZMh5NQoGbfAUd92ibgm2c09l67EfkFoah79XHiviQEwsicklTVSq02xWxtmEpS31HAYp28g5Q+DhcBYCasf4dvjlxtjUeszM1IS4GBD6OrZApcYQlrvKh+skQNj8vz07ZBRAoGAWZ2n1o+n6COIN548mVDiljURZiSyulVNgWflWqni/CykofWfLYx86fTymi44D/MWz1jeNuXt0fhYEwxRRC+02VKhM6Bfkxk9wucLhsOGVhmK8CdoLP7U7br+MKF6uabDcAmCVDFWq14v3/KxN3VxSunjeGOrrzf5PNz6s2jgNaQ=
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwifIBVf/tuM4kMQBy/Jm6enhyW0sY5N1bHS+EFTPoxc+cmFE9EncX0B/csRg9bKxV2ZsMsBbEs64xjer+SHkMjshDgeeW4yPshc3ct0foDZY6ndeff/7jBpluexZcQE1M0APHSmADxmcwHvIIKhBVMEwRGf749TyNPNOh07l6bnunihgh+eYkWdPJYnIdcctvuDLPLtZY0swP1+J3jxAEU5xoOCAIW6sPqUKom/fbZnEnUTN14rtySq1luF5X/Y8B/ZVQ644TqDcT63/ebOUdqnrjfoHi8qk5/P3eddl+siNaKIXhjgBLiYRwlVKLdSKa8dzp4gJxExXNhvtQKcT2wIDAQAB
    notify-url: http://y48ad8d6.natappfree.cc/api/v1/payments/alipay/notify
    return-url: http://localhost:8080/doc.html